stages:
  NH2OTrajectory:
    cmd: zntrack run humf_experiments.nodes.n_h2o_trajectory.NH2OTrajectory --name
      NH2OTrajectory
    deps:
    - data/h2o_trajectory
    params:
    - NH2OTrajectory
    outs:
    - nodes/NH2OTrajectory/dumped_forces.txt
    - nodes/NH2OTrajectory/energy.xvg
    - nodes/NH2OTrajectory/reduced.gro
    metrics:
    - nodes/NH2OTrajectory/node-meta.json:
        cache: false
  CreateGromacsDataset:
    cmd: zntrack run humf_experiments.nodes.create_gromacs_dataset.CreateGromacsDataset
      --name CreateGromacsDataset
    deps:
    - nodes/NH2OTrajectory/dumped_forces.txt
    - nodes/NH2OTrajectory/energy.xvg
    - nodes/NH2OTrajectory/node-meta.json
    - nodes/NH2OTrajectory/reduced.gro
    outs:
    - nodes/CreateGromacsDataset/data
    metrics:
    - nodes/CreateGromacsDataset/node-meta.json:
        cache: false
  ConvertTrajectoryToOrcaInputs:
    cmd: zntrack run 
      humf_experiments.nodes.convert_trajectory_to_orca_inputs.ConvertTrajectoryToOrcaInputs
      --name ConvertTrajectoryToOrcaInputs
    deps:
    - nodes/NH2OTrajectory/dumped_forces.txt
    - nodes/NH2OTrajectory/energy.xvg
    - nodes/NH2OTrajectory/node-meta.json
    - nodes/NH2OTrajectory/reduced.gro
    params:
    - ConvertTrajectoryToOrcaInputs
    outs:
    - nodes/ConvertTrajectoryToOrcaInputs/frames
    metrics:
    - nodes/ConvertTrajectoryToOrcaInputs/node-meta.json:
        cache: false
  CreateOrcaDataset:
    cmd: zntrack run humf_experiments.nodes.create_orca_dataset.CreateOrcaDataset
      --name CreateOrcaDataset
    deps:
    - nodes/ConvertTrajectoryToOrcaInputs/frames
    - nodes/ConvertTrajectoryToOrcaInputs/node-meta.json
    outs:
    - nodes/CreateOrcaDataset/data
    metrics:
    - nodes/CreateOrcaDataset/node-meta.json:
        cache: false
  TrainModel:
    cmd: zntrack run humf_experiments.nodes.train_model.TrainModel --name TrainModel
    deps:
    - nodes/CreateOrcaDataset/data
    - nodes/CreateOrcaDataset/node-meta.json
    params:
    - TrainModel
    outs:
    - nodes/TrainModel/logs
    - nodes/TrainModel/models
    metrics:
    - nodes/TrainModel/node-meta.json:
        cache: false
