ConvertTrajectoryToOrcaInputs:
    charge: '0'
    every_nth_frame: 10
    method_and_basisset: B3LYP def2-TZVP D3BJ
    multiplicity: '1'
    pal: '1'
    run_orca: true
NH2OTrajectory:
    concatenate: 1
    num_molecules: 3
evaluate_ljc_water_on_CreateGromacsDataset:
    model: ljc_water
evaluate_ljc_water_on_CreateOrcaDataset:
    model: ljc_water
evaluate_polynomial_water_on_CreateGromacsDataset:
    model: polynomial_water
evaluate_polynomial_water_on_CreateOrcaDataset:
    model: polynomial_water
fit_ljc_water_to_CreateGromacsDataset:
    max_epochs: 1000
    model: ljc_water
fit_ljc_water_to_CreateOrcaDataset:
    max_epochs: 1000
    model: ljc_water
fit_polynomial_water_to_CreateGromacsDataset:
    max_epochs: 1000
    model: polynomial_water
fit_polynomial_water_to_CreateOrcaDataset:
    max_epochs: 1000
    model: polynomial_water
