ConvertTrajectoryToOrcaInputs:
  charge: '0'
  every_nth_frame: 10
  method_and_basisset: B3LYP def2-TZVP D3BJ
  multiplicity: '1'
  pal: '1'
  run_orca: true
NH2OTrajectory:
  concatenate: 1
  num_molecules: 3
evaluate_ljc_water_on_gromacs:
  model: ljc_water
evaluate_ljc_water_on_orca:
  model: ljc_water
evaluate_polynomial_water_on_gromacs:
  model: polynomial_water
evaluate_polynomial_water_on_orca:
  model: polynomial_water
fit_ljc_water_to_gromacs:
  batch_size: 32
  learning_rate: 0.001
  max_epochs: 100
  model: ljc_water
  seed: 42
  trade_off: 0
fit_ljc_water_to_orca:
  batch_size: 32
  learning_rate: 0.1
  max_epochs: 1000
  model: ljc_water
  seed: 42
  trade_off: 1
fit_polynomial_water_to_gromacs:
  batch_size: 32
  learning_rate: 0.001
  max_epochs: 100
  model: polynomial_water
  seed: 42
  trade_off: 0
fit_polynomial_water_to_orca:
  batch_size: 32
  learning_rate: 0.001
  max_epochs: 100
  model: polynomial_water
  seed: 42
  trade_off: 0
