get_3_h2o_trajectory:
    concatenate: 1
    num_molecules: 3
run_orca:
    charge: '0'
    every_nth_frame: 10
    method_and_basisset: B3LYP def2-TZVP D3BJ
    multiplicity: '1'
    pal: '1'
    run_orca: true
train_model:
    max_epochs: 10
